-- V4_014C synthetic commercial schema bootstrap.
-- Ephemeral PostgreSQL only. Never run against production.

create schema if not exists auth;
create schema if not exists private;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  else
    alter role service_role bypassrls;
  end if;
end
$$;

grant usage on schema public to anon, authenticated, service_role;
grant usage on schema auth to authenticated, service_role;
grant usage on schema private to authenticated, service_role;

create or replace function auth.uid()
returns uuid
language sql
stable
security invoker
set search_path = ''
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
grant execute on function auth.uid() to authenticated, service_role;

create table public.organizations (
  id uuid primary key,
  code text not null unique,
  name text not null,
  active boolean not null default true
);

create table public.departments (
  id uuid primary key,
  organization_id uuid not null references public.organizations(id),
  code text not null,
  name text not null,
  parent_id uuid references public.departments(id),
  sort_order integer not null default 0,
  active boolean not null default true
);

create table public.warehouses (
  id uuid primary key,
  organization_id uuid not null references public.organizations(id),
  org_unit_id uuid references public.departments(id),
  code text not null,
  name text not null,
  active boolean not null default true
);

create table public.organization_members (
  id uuid primary key,
  organization_id uuid not null references public.organizations(id),
  user_id uuid not null,
  status text not null check (status in ('INVITED','ACTIVE','SUSPENDED','DISABLED')),
  display_name text,
  email text,
  joined_at timestamptz default now(),
  unique (organization_id, user_id)
);

create table public.permissions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id),
  actor_user_id uuid,
  actor_membership_id uuid references public.organization_members(id),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  old_value jsonb,
  new_value jsonb,
  source_type text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table private.test_scoped_permissions_v4 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  organization_id uuid not null references public.organizations(id),
  permission_code text not null,
  warehouse_id uuid references public.warehouses(id),
  org_unit_id uuid references public.departments(id)
);

-- PostgreSQL primary keys treat NULL as distinct, so use a matching unique
-- expression for organization-scope grants.
create unique index test_scoped_permissions_v4_scope_uidx
on private.test_scoped_permissions_v4(
  user_id,
  organization_id,
  permission_code,
  coalesce(warehouse_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(org_unit_id, '00000000-0000-0000-0000-000000000000'::uuid)
);

create or replace function private.has_scoped_permission_v4(
  p_organization_id uuid,
  p_permission_code text,
  p_warehouse_id uuid default null,
  p_org_unit_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from private.test_scoped_permissions_v4 sp
    join public.organization_members om
      on om.organization_id = sp.organization_id
     and om.user_id = sp.user_id
     and om.status = 'ACTIVE'
    where sp.user_id = (select auth.uid())
      and sp.organization_id = p_organization_id
      and sp.permission_code = p_permission_code
      and (
        (sp.warehouse_id is null and sp.org_unit_id is null)
        or (sp.warehouse_id is not null and sp.warehouse_id = p_warehouse_id)
        or (sp.org_unit_id is not null and sp.org_unit_id = p_org_unit_id)
      )
  );
$$;

revoke all on function private.has_scoped_permission_v4(uuid,text,uuid,uuid)
  from public, anon, authenticated, service_role;
grant execute on function private.has_scoped_permission_v4(uuid,text,uuid,uuid)
  to authenticated, service_role;

grant select on public.organizations, public.departments, public.warehouses,
  public.organization_members, public.permissions to authenticated, service_role;
grant select on public.audit_logs to authenticated, service_role;
grant select on private.test_scoped_permissions_v4 to authenticated, service_role;

insert into public.permissions(code)
values ('workflow.view'), ('workflow.manage');

-- Organizations
insert into public.organizations(id, code, name) values
  ('10000000-0000-4000-8000-000000000001','ORG-A','Synthetic Pharmacy A'),
  ('10000000-0000-4000-8000-000000000002','ORG-B','Synthetic Pharmacy B');

-- Org units and warehouses
insert into public.departments(id, organization_id, code, name) values
  ('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','A-UNIT','A Unit'),
  ('20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002','B-UNIT','B Unit');

insert into public.warehouses(id, organization_id, org_unit_id, code, name) values
  ('30000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','A-WH','A Warehouse'),
  ('30000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002','20000000-0000-4000-8000-000000000002','B-WH','B Warehouse');

-- Users / memberships
insert into public.organization_members(
  id, organization_id, user_id, status, display_name, email
) values
  ('40000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000001','ACTIVE','Manager A','manager-a@example.invalid'),
  ('40000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002','ACTIVE','Staff A','staff-a@example.invalid'),
  ('40000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000002','50000000-0000-4000-8000-000000000003','ACTIVE','Manager B','manager-b@example.invalid');

-- Manager A: org-wide workflow.view + workflow.manage.
insert into private.test_scoped_permissions_v4(user_id, organization_id, permission_code)
values
  ('50000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','workflow.view'),
  ('50000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','workflow.manage');

-- Staff A: read only.
insert into private.test_scoped_permissions_v4(user_id, organization_id, permission_code)
values
  ('50000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','workflow.view');

-- Manager B: org-wide B only.
insert into private.test_scoped_permissions_v4(user_id, organization_id, permission_code)
values
  ('50000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000002','workflow.view'),
  ('50000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000002','workflow.manage');
